### PR TITLE
Rack middlewares

### PR DESCRIPTION
**Pull request by bibendi**
### What is the purpose of this pull request?

Want to use a request session.

### What changes did you make? (overview)

- [x] Added middleware stack.
- [x] Run that stack when creating a request.

### CODE REVIEW

**Comment by bibendi** [comment]
Now that just works without extra code https://github.com/evilmartians/evil_chat/pull/5/files#diff-915d99197df5caa102c51760df5a7029R6

**Comment by pjforde1978** [comment]
Hi @bibendi, I've been getting some help from @palkan in my attempts to get AnyCable working easily with https://github.com/hopsoft/stimulus_reflex/issues/46 and currently the only remaining blocker is session handling.

I have checked out and installed this PR on my local system. So far as I can tell, session.id and session.fetch("id", nil) both return nil.

I only learned about the session.fetch syntax from your evil_chat PR5 linked above. Technically we could notify our developers that they would need to adopt this fetch syntax, but ideally it would be even more amazing if people could use the shorter session.id format they are familiar with. Otherwise, it's not technically a "drop-in" replacement. :grin: 

If there's anything I'm missing or anything I can do to assist/test further, please let me know.

**Comment by bibendi** [comment]
Hey @pjforde1978 
Can you please provide me a branch where I can run and debug an application to see what's going on and find a problem?

**Comment by pjforde1978** [comment]
@bibendi no problem!

https://github.com/pjforde1978/stimulus_reflex_todomvc/tree/anycable

Note that this is currently configured to look for anycable in ../anycable so take a quick look at the Gemfile.

Right now, I've been doing all of my experimentation in the create method of the todos reflex class. Line 13 is supposed to be session_id: session.id as you can guess. It is, therefore, not working and anything you can see is hugely appreciated.

https://github.com/pjforde1978/stimulus_reflex_todomvc/blob/b7fbca3bfb408a5183b0ae10b494d888393cfd04/app/reflexes/todos_reflex.rb#L13

**Comment by bibendi** [comment]
Well, I've started the app, and I think I've found the problem.

You are using `session` in a Channel, but `session` is only accessible in Connection. As far as I know, you will get the same error if you would run vanilla ActionCable in real production mode as [standalone process](https://edgeguides.rubyonrails.org/action_cable_overview.html#standalone).

I've tried to fix that with a code bellow:

```diff
diff --git a/app/channels/application_cable/connection.rb b/app/channels/application_cable/connection.rb
index 0ff5442..2f821fb 100644
--- a/app/channels/application_cable/connection.rb
+++ b/app/channels/application_cable/connection.rb
@@ -1,4 +1,10 @@
 module ApplicationCable
   class Connection < ActionCable::Connection::Base
+    identified_by :session_id
+
+    def connect
+      self.session_id = session.id
+      reject_unauthorized_connection unless session_id
+    end
   end
 end
diff --git a/app/reflexes/todos_reflex.rb b/app/reflexes/todos_reflex.rb
index 6253544..fba3666 100644
--- a/app/reflexes/todos_reflex.rb
+++ b/app/reflexes/todos_reflex.rb
@@ -1,16 +1,8 @@
 class TodosReflex < StimulusReflex::Reflex
+  delegate :session_id, to: :channel
+
   def create
-    # puts channel.public_methods
-    # puts ActionDispatch::Request.new(connection.env).cookie_jar.inspect
-    # puts Rails.application.env_config
-    # puts "*"
-    # puts ActionDispatch::Request.new(Rails.application.env_config.merge(connection.env)).cookie_jar.encrypted[Rails.application.config.session_options[:key]]
-    # puts "*"
-    # .fetch(Rails.application.config.session_options[:key])
-    # puts ActionDispatch::Session::CookieStore
-    # id = ActionController.cookies.encrypted[Rails.application.config.session_options[:key]]
-    puts session.fetch("id", nil)
-    Todo.create session_id: session.fetch("id", nil), title: element[:value]
+    Todo.create session_id: session_id, title: element[:value]
   end
 
   def edit
@@ -22,27 +14,28 @@ class TodosReflex < StimulusReflex::Reflex
   end
 
   def update
-    Todo.find_by(session_id: session.id, id: element.dataset[:id])&.update title: element[:value]
+    Todo.find_by(session_id: session_id, id: element.dataset[:id])&.update title: element[:value]
   end
 
   def toggle
-    Todo.find_by(session_id: session.id, id: element.dataset[:id])&.toggle! :completed
+    Todo.find_by(session_id: session_id, id: element.dataset[:id])&.toggle! :completed
   end
 
   def destroy
-    Todo.find_by(session_id: session.id, id: element.dataset[:id])&.destroy
+    Todo.find_by(session_id: session_id, id: element.dataset[:id])&.destroy
   end
 
   def toggle_all
-    todos = Todo.where(session_id: session.id)
+    todos = Todo.where(session_id: session_id)
     todos.update_all completed: todos.active.exists?
   end
 
   def destroy_completed
-    Todo.where(session_id: session.id, completed: true).destroy_all
+    Todo.where(session_id: session_id, completed: true).destroy_all
   end
 
   def filter
+    # FIXME: cannot use session and cookies when connection was established
     session[:filter] = element.dataset[:filter]
   end
 end
```

**Comment by pjforde1978** [comment]
Just looping in @hopsoft for sanity checking.

Thanks so much for taking a crack at this. The way the library is set up, session is delegated to a request object as seen here: https://github.com/hopsoft/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb

It's my guess that the session comes through that request, which is passed connection.env when it's created.

What I can say is that session in StimulusReflex works great with vanilla action cable. We use session all of the time in our apps.

You can see it working on any of these examples live: https://expo-pjf.herokuapp.com/demos/todo

If you expand the Ruby code browser at the bottom of the screen and inspect todos_reflex.rb you'll see that it is as described.

(Apologies that is not the usual URL for our expo site, but the main site is currently down.)

One question I can address is that the session is initially established in TodosController#show so there should be a session object in scope by the time StimulusReflex kicks in.

**Comment by bibendi** [comment]
> What I can say is that session in StimulusReflex works great with vanilla action cable. We use session all of the time in our apps.

Do you run an ActionCable websocket server as a standalone Rack application?

**Comment by pjforde1978** [comment]
I don't even know how to do that. :grin: 

We just fire up `rails s` like champs and everything works.

**Comment by bibendi** [comment]
[Channels](https://api.rubyonrails.org/classes/ActionCable/Channel/Base.html) are long-lived objects. So, you should avoid using cookies in them. Cookies in a channel belong to an initial connection request and then have never changed. In terms of AnyCable, channels short-lived objects, and they have no access to an initial connection request.

My question regarding a standalone server was just a clarification that using a session object in channels is bad practice because, in terms of real loaded ActionCable production server, you would not get access to the session because of a standalone ActionCable server doesn't have Rack-middlewares stack. And in a simple (i.e., development) usage allows you to do that because it's kind of side effect because a connection request goes through that stack before will be hijacked as a socket connection.

@palkan WDYT can we send request headers from a WS server to an RPC server not only when establishing a connection? Or it is a bad practice because if cookies would change in the main application, then WS would not know about it?

**Comment by hopsoft** [comment]
>  in terms of real loaded ActionCable production server, you would not get access to the session because of a standalone ActionCable server doesn't have Rack-middlewares stack

This is a great point and is a use case that StimulusReflex needs to validate and ensure works out of the box. I'll do that this week sometime.

**Comment by palkan** [comment]
@bibendi 

> WDYT can we send request headers from a WS server to an RPC server not only when establishing a connection? Or it is a bad practice because if cookies would change in the main application, then WS would not know about it?

Well, I'm kinda against exposing request objects to channels, because violates the SoC principle. I believe that channels should only know about the connection object and its interface (i.e., identifiers).

But... Rails doesn't care about principles 🙂 That's not that bad: we can build smth like Stimulus Reflex by utilizing these imperfections.

That's why I'm thinking about making request available in channels for AnyCable 1.0, 'cause one of the goals for AnyCable 1.0 is the maximum Action Cable compatibility (AnyCable 2.0 likely won't depend on Action Cable at all).

**Comment by daya** [comment]
@palkan any plans to release this merge? this will be very helpful for [hopsoft/stimulus_reflex/issues/46](https://github.com/hopsoft/stimulus_reflex/issues/46)

**Comment by palkan** [comment]
@daya I plan to release the first preview version of v1.0 (including this feature and other StimulusReflex related improvements) later this week.

I will write an update and instructions on how to use it in hopsoft/stimulus_reflex/issues/46.

**Comment by daya** [comment]
@palkan Thank you so very much. :bowing_man:

**Comment by leastbad** [comment]
This is excellent news. Thanks for all of your hard work, @palkan and @bibendi.

If anyone ever has questions about StimulusReflex please consider yourself welcome in our Discord server. Looking at you, @daya! ;)

**Comment by daya** [comment]
@leastbad I am probably overloading this issue but what's the URL to SR's discord server?

**Comment by hopsoft** [comment]
https://discord.gg/XveN625

**Pull request merged**
